# .github/release.yml
changelog:
  categories:
    - title: ğŸ› Bug Fix
      labels:
        - ğŸ› fix
    - title: ğŸ¨ Style Changes
      labels:
        - ğŸ¨ style
    - title: ğŸ“˜ Docs Changes
      labels:
        - ğŸ“˜ docs
    - title: Other Changes
      labels:
        - "*"
